### ISSUE TITLE
NFPropulsion/Kerbal Atomics support

### ISSUE THREAD

**Issue by TotallyNotHuman** [ValiZockt/RealFuels-Stock#12]
Near Future Propulsion: I'm not sure about the patch in `000_NeedsRework`. It reduces the EC consumption of the ion thrusters to a ridiculously small amount, but that might be more realistic since it was grandfathered in from Raptor831's RFStock.
If this patch was applied to all engines it would make the reactors from Electrical less useful though.

Kerbal Atomics: Should be fairly simple, I can probably hammer out a patch for it.

**Comment by ValentinBischof** [comment]
I'll have to admit, that I don't know anything about Ion Engines. I know the basic principle of them, but I've never really read through stuff about Ion Engines (and I actually never play with them) so im fairly inexperienced with balancing them. That's why left them untouched when taking over RF-Stock. If you know any better would really appreciate your help there.

**Comment by TotallyNotHuman** [comment]
I don't know how ion engines work either, but my understanding of the power draw being as high as they are in stock(alike) is because the thrust is also scaled up. If ion engines had real-life stats in game it would probably need PersistentThrust or something similar to be viable. I think NFP is fairly balanced in that regard, especially when used in tandem with NFE reactors.
